backend:
  name: github
  repo: hakkurgithub/GitHubmimari # GitHub kullanıcı adı ve repo adı
  branch: main
  auth_type: "oauth"

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menü Ürünleri"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Ürün Adı", name: "name", widget: "string" }
      - { label: "Açıklama", name: "description", widget: "text" }
      - { label: "Fiyat (₺)", name: "price", widget: "number" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Döner", "Kebap", "Pide", "İçecekler", "Tatlılar"] }
      - { label: "Resim", name: "image", widget: "image", required: false }
      - { label: "Kalori", name: "calories", widget: "number", required: false }
      - { label: "Vegetaryen", name: "isVegetarian", widget: "boolean", default: false }
      - { label: "Vegan", name: "isVegan", widget: "boolean", default: false }
      - { label: "Glutensiz", name: "isGlutenFree", widget: "boolean", default: false }
      - { label: "Aktif", name: "isActive", widget: "boolean", default: true }
  
  - name: "pages"
    label: "Sayfalar"
    files:
      - label: "Hakkımızda Sayfası"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
          - { label: "Resim", name: "image", widget: "image", required: false }
      
      - label: "İletişim Sayfası"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Telefon", name: "phone", widget: "string" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }
          - { label: "Adres", name: "address", widget: "text" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Çalışma Saatleri", name: "workingHours", widget: "text" }
          - { label: "Harita URL", name: "mapUrl", widget: "string", required: false }
      
      - label: "Ana Sayfa"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: "Hero Başlık", name: "heroTitle", widget: "string" }
          - { label: "Hero Alt Başlık", name: "heroSubtitle", widget: "text" }
          - { label: "Hero Resim", name: "heroImage", widget: "image" }
          - { label: "Özellikler", name: "features", widget: "list", fields: [
              { label: "Başlık", name: "title", widget: "string" },
              { label: "Açıklama", name: "description", widget: "text" },
              { label: "İkon", name: "icon", widget: "string" }
            ]}
  
  - name: "announcements"
    label: "Duyurular"
    folder: "content/announcements"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "İçerik", name: "body", widget: "markdown" }
      - { label: "Tarih", name: "date", widget: "datetime" }
      - { label: "Aktif", name: "isActive", widget: "boolean", default: true }
      - { label: "Öncelik", name: "priority", widget: "select", options: ["düşük", "orta", "yüksek"], default: "orta" }